# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0" 
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"
  - "push_to_ecr"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "daniel-VGW/CodeFresh-HelloWorld"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "daniel-VGW/CodeFresh-HelloWorld"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: true

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: ${{build}}
    working_directory: "${{clone}}" # Running command where code cloned
     
    commands:
      - "ls"
      - "npm run test2"

    stage: "test"

  push_to_ecr:
    type: push
    title: Push to ECR
    description: Pushing docker image to ecr
    candidate: ${{build}}
    tag: latest
    registry: hello-world
    fail_fast: false
    stage: "push_to_ecr"